services:
  rtbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rtlab-autotrader
    working_dir: /app
    env_file:
      - ../.env
    volumes:
      - ..:/app
    ports:
      - "8080:8080"
    command: []
    restart: unless-stopped
